#!/bin/bash
# amp_check.sh - ONE command to validate a kernel, no manual wrapper editing.
#
# For a kernel matching the common GEMM shape:
#   __global__ void <fn>(const float* A, const float* B, float* C,
#                         int M, int N, int K)
# this auto-detects your toolchain (nvcc or hipcc), generates the
# amp_plugin.h wrapper, compiles it, builds AMP if needed, and runs
# amp_validate_kernel -- one command on each machine instead of five.
#
# Usage: bash scripts/amp_check.sh <kernel.cu> <kernel_function_name> [M N K]
#
# If your kernel has a different signature (extra params, different
# arg order), this won't fit -- use scripts/amp_generate_wrapper.py
# directly and edit the two TODOs by hand instead.
set -e

KERNEL_FILE="$1"
KERNEL_FN="$2"
M="${3:-512}"; N="${4:-512}"; K="${5:-512}"

if [ -z "$KERNEL_FILE" ] || [ -z "$KERNEL_FN" ]; then
    cat <<USAGE
Usage: bash scripts/amp_check.sh <kernel.cu> <kernel_function_name> [M N K]

One-command validation for a kernel matching:
  __global__ void <kernel_function_name>(const float* A, const float* B,
                                          float* C, int M, int N, int K)

Different signature? Generate + hand-edit a wrapper instead:
  python3 scripts/amp_generate_wrapper.py <kernel_function_name>
USAGE
    exit 2
fi

if [ ! -f "$KERNEL_FILE" ]; then
    echo "No such file: $KERNEL_FILE" >&2
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
KERNEL_ABS="$(cd "$(dirname "$KERNEL_FILE")" && pwd)/$(basename "$KERNEL_FILE")"
WORKDIR="$(mktemp -d)"
trap 'rm -rf "$WORKDIR"' EXIT

if command -v nvcc >/dev/null 2>&1 && nvidia-smi >/dev/null 2>&1; then
    COMPILER=nvcc; SUFFIX=cuda; EXTRA_FLAGS="-Xcompiler -fPIC"
    echo "Detected: NVIDIA (nvcc)"
elif command -v hipcc >/dev/null 2>&1; then
    COMPILER=hipcc; SUFFIX=hip; EXTRA_FLAGS="-fPIC"
    echo "Detected: AMD (hipcc)"
else
    echo "No nvcc or hipcc found in PATH -- can't compile a kernel here." >&2
    exit 1
fi

WRAPPER="$WORKDIR/amp_auto_wrapper.cu"
cat > "$WRAPPER" <<EOF
// Auto-generated by amp_check.sh -- wraps $KERNEL_FN() from
// $KERNEL_FILE for amp_validate_kernel. See include/amp_plugin.h.
//
// hip_runtime.h/cuda_runtime.h MUST come before the #include of the
// user's kernel file below -- blockIdx/blockDim/threadIdx aren't
// available until the runtime header is included, even though
// __global__ itself is recognized as soon as hipcc/nvcc compiles the
// file in device mode. Confirmed the hard way: including the kernel
// file first produced "use of undeclared identifier 'blockIdx'" on
// real MI300X hardware.
#if defined(__HIPCC__)
  #include <hip/hip_runtime.h>
  #define GPU_MALLOC      hipMalloc
  #define GPU_FREE        hipFree
  #define GPU_MEMCPY_H2D(d,s,n) hipMemcpy(d,s,n,hipMemcpyHostToDevice)
  #define GPU_MEMCPY_D2H(d,s,n) hipMemcpy(d,s,n,hipMemcpyDeviceToHost)
  #define GPU_SYNC        hipDeviceSynchronize
  #define GPU_SUCCESS     hipSuccess
#else
  #include <cuda_runtime.h>
  #define GPU_MALLOC      cudaMalloc
  #define GPU_FREE        cudaFree
  #define GPU_MEMCPY_H2D(d,s,n) cudaMemcpy(d,s,n,cudaMemcpyHostToDevice)
  #define GPU_MEMCPY_D2H(d,s,n) cudaMemcpy(d,s,n,cudaMemcpyDeviceToHost)
  #define GPU_SYNC        cudaDeviceSynchronize
  #define GPU_SUCCESS     cudaSuccess
#endif

#include "$KERNEL_ABS"

extern "C" int amp_user_gemm_fp32(const float* hA, const float* hB, float* hC,
                                   int M, int N, int K) {
    float *dA = nullptr, *dB = nullptr, *dC = nullptr;
    if (GPU_MALLOC(&dA, (size_t)M * K * sizeof(float)) != GPU_SUCCESS) return 1;
    if (GPU_MALLOC(&dB, (size_t)K * N * sizeof(float)) != GPU_SUCCESS) return 1;
    if (GPU_MALLOC(&dC, (size_t)M * N * sizeof(float)) != GPU_SUCCESS) return 1;
    GPU_MEMCPY_H2D(dA, hA, (size_t)M * K * sizeof(float));
    GPU_MEMCPY_H2D(dB, hB, (size_t)K * N * sizeof(float));
    dim3 block(16, 16);
    dim3 grid((N + block.x - 1) / block.x, (M + block.y - 1) / block.y);
    $KERNEL_FN<<<grid, block>>>(dA, dB, dC, M, N, K);
    if (GPU_SYNC() != GPU_SUCCESS) { GPU_FREE(dA); GPU_FREE(dB); GPU_FREE(dC); return 1; }
    GPU_MEMCPY_D2H(hC, dC, (size_t)M * N * sizeof(float));
    GPU_FREE(dA); GPU_FREE(dB); GPU_FREE(dC);
    return 0;
}
EOF

LIB="$WORKDIR/libamp_check_$SUFFIX.so"
echo "=== Wrapping & compiling $KERNEL_FN ==="
if ! "$COMPILER" -shared $EXTRA_FLAGS "$WRAPPER" -o "$LIB" 2>"$WORKDIR/compile.log"; then
    cat "$WORKDIR/compile.log" >&2
    echo "" >&2
    echo "Auto-wrap failed to compile -- your kernel's signature likely doesn't" >&2
    echo "match (const float* A, const float* B, float* C, int M, int N, int K)." >&2
    echo "Generate a wrapper to hand-edit instead:" >&2
    echo "  python3 $SCRIPT_DIR/amp_generate_wrapper.py $KERNEL_FN" >&2
    exit 1
fi

VALIDATOR="$PROJECT_DIR/build/amp_validate_kernel"
if [ ! -x "$VALIDATOR" ]; then
    echo "=== amp_validate_kernel not built yet -- building AMP first ==="
    bash "$SCRIPT_DIR/build_auto.sh" >/dev/null
fi

DUMP="$PROJECT_DIR/${SUFFIX}_dump.json"
echo "=== Validating against CPU reference (M=$M N=$N K=$K) ==="
"$VALIDATOR" "$LIB" "$DUMP" "$M" "$N" "$K"

echo ""
echo "Dump written to: $DUMP"
echo "Run this same command on the other vendor's machine, then:"
echo "  python3 scripts/parity_check.py cuda_dump.json hip_dump.json --analyze"
