#!/usr/bin/env python3
"""Generate an include/amp_plugin.h-compliant wrapper around YOUR kernel,
so you don't hand-write the boilerplate device malloc/memcpy/launch/free
dance every time.

Usage:
    python3 scripts/amp_generate_wrapper.py my_gemm_kernel --output my_wrapper.cu

Generates a .cu file with:
  - a forward declaration of <kernel_name>(...) for you to point at your
    real kernel (replace the declaration with an #include of your actual
    header, or paste your kernel body in directly)
  - the extern "C" amp_user_gemm_fp32(...) wrapper amp_validate_kernel
    looks for, doing the device malloc/copy-in/launch/copy-out/free/sync
    sequence around a call to <kernel_name>

The generated file compiles unmodified with either nvcc or hipcc (see
the header comment it writes), matching examples/user_plugin_example.cu.
This does not invent a kernel for you -- it only removes the boilerplate
around calling the one you already have.
"""
import argparse
import sys

TEMPLATE = '''\
// {wrapper_file} - generated by scripts/amp_generate_wrapper.py
// Wraps your kernel `{kernel_name}` for amp_validate_kernel.
// See include/amp_plugin.h for the contract this implements.
//
// Build:
//   nvcc  -shared -Xcompiler -fPIC {wrapper_file} -o lib{stem}_cuda.so
//   hipcc -shared -fPIC          {wrapper_file} -o lib{stem}_hip.so
//
// Validate:
//   ./amp_validate_kernel lib{stem}_cuda.so cuda_dump.json {m} {n} {k}
//   ./amp_validate_kernel lib{stem}_hip.so  hip_dump.json  {m} {n} {k}
//   python3 scripts/parity_check.py cuda_dump.json hip_dump.json

#if defined(__HIPCC__)
  #include <hip/hip_runtime.h>
  #define GPU_MALLOC      hipMalloc
  #define GPU_FREE        hipFree
  #define GPU_MEMCPY_H2D(d,s,n) hipMemcpy(d,s,n,hipMemcpyHostToDevice)
  #define GPU_MEMCPY_D2H(d,s,n) hipMemcpy(d,s,n,hipMemcpyDeviceToHost)
  #define GPU_SYNC        hipDeviceSynchronize
  #define GPU_SUCCESS     hipSuccess
#else
  #include <cuda_runtime.h>
  #define GPU_MALLOC      cudaMalloc
  #define GPU_FREE        cudaFree
  #define GPU_MEMCPY_H2D(d,s,n) cudaMemcpy(d,s,n,cudaMemcpyHostToDevice)
  #define GPU_MEMCPY_D2H(d,s,n) cudaMemcpy(d,s,n,cudaMemcpyDeviceToHost)
  #define GPU_SYNC        cudaDeviceSynchronize
  #define GPU_SUCCESS     cudaSuccess
#endif

// --- TODO: point this at your real kernel ---
// Replace this forward declaration with an #include of your kernel's
// header, or paste your __global__ kernel definition here directly.
// Expected signature: row-major A (MxK), B (KxN), C (MxN).
__global__ void {kernel_name}(const float* A, const float* B, float* C,
                               int M, int N, int K{extra_params});

extern "C" int amp_user_gemm_fp32(const float* hA, const float* hB, float* hC,
                                   int M, int N, int K) {{
    float *dA = nullptr, *dB = nullptr, *dC = nullptr;
    if (GPU_MALLOC(&dA, (size_t)M * K * sizeof(float)) != GPU_SUCCESS) return 1;
    if (GPU_MALLOC(&dB, (size_t)K * N * sizeof(float)) != GPU_SUCCESS) return 1;
    if (GPU_MALLOC(&dC, (size_t)M * N * sizeof(float)) != GPU_SUCCESS) return 1;

    GPU_MEMCPY_H2D(dA, hA, (size_t)M * K * sizeof(float));
    GPU_MEMCPY_H2D(dB, hB, (size_t)K * N * sizeof(float));

    // --- TODO: set your kernel's real launch config ---
    dim3 block({block_x}, {block_y});
    dim3 grid((N + block.x - 1) / block.x, (M + block.y - 1) / block.y);
    {kernel_name}<<<grid, block>>>(dA, dB, dC, M, N, K{extra_args});

    if (GPU_SYNC() != GPU_SUCCESS) {{ GPU_FREE(dA); GPU_FREE(dB); GPU_FREE(dC); return 1; }}

    GPU_MEMCPY_D2H(hC, dC, (size_t)M * N * sizeof(float));

    GPU_FREE(dA); GPU_FREE(dB); GPU_FREE(dC);
    return 0;
}}
'''


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                  formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("kernel_name", help="name of your existing __global__ kernel function")
    ap.add_argument("--output", "-o", default=None,
                     help="output .cu file path (default: <kernel_name>_wrapper.cu)")
    ap.add_argument("--block", default="16,16",
                     help="thread block dims as X,Y (default: 16,16)")
    ap.add_argument("--shape", default="512,512,512",
                     help="default M,N,K to print in the build/validate comment (default: 512,512,512)")
    ap.add_argument("--extra-arg", action="append", default=[],
                     help="extra kernel parameter beyond (A,B,C,M,N,K), as 'type name' "
                          "(repeatable). The wrapper forwards nothing for these -- "
                          "edit the generated file to supply real values.")
    args = ap.parse_args()

    out_path = args.output or f"{args.kernel_name}_wrapper.cu"
    block_x, block_y = (args.block.split(",") + ["16", "16"])[:2]
    m, n, k = (args.shape.split(",") + ["512", "512", "512"])[:3]

    extra_params = "".join(f", {a}" for a in args.extra_arg)
    extra_args = "".join(f", /*TODO*/ {a.split()[-1]}" for a in args.extra_arg)

    stem = args.kernel_name

    content = TEMPLATE.format(
        wrapper_file=out_path, kernel_name=args.kernel_name, stem=stem,
        m=m, n=n, k=k, block_x=block_x, block_y=block_y,
        extra_params=extra_params, extra_args=extra_args,
    )

    with open(out_path, "w") as f:
        f.write(content)

    print(f"Wrote {out_path}")
    print("Next: edit the two TODOs inside (point at your real kernel, set launch config), then:")
    print(f"  nvcc  -shared -Xcompiler -fPIC {out_path} -o lib{stem}_cuda.so")
    print(f"  ./amp_validate_kernel lib{stem}_cuda.so cuda_dump.json {m} {n} {k}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
